version: '2'
services:
    hideed-app:
        image: hideed
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://hideed-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=hideed
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hideed-mongodb:
        extends:
            file: mongodb.yml
            service: hideed-mongodb
